1:
  break_after_n_trials: 0
  crossed_edges:
    graphs_with_crossed: false
    graphs_without_crossed_edges: true
  n_of_trials: null
  no_of_edges:
    '3': true
    '4': false
    '5': false
  predefined_test: MIX.csv
  predefined_training: 12_trials.csv
  randomize_graphs: false
  randomize_trials_order: false
  session_type: Predefined test
  training_accuracy: 0.55
  training_attempts: 5
  training_session: true
  trials_per_cell: null
  types_of_target_vertices:
    direct: true
    indirect: true
2:
  break_time: 1.0
  click_show_time: false
  clock_position_x: 0
  clock_position_y: 200
  clock_size: 100
  clock_time: 5.0
  left_button_color: '#ffff00'
  mouse_buttons_position_x: 0
  mouse_buttons_position_y: -250
  mouse_buttons_size: 100
  one_target: false
  right_button_color: '#0000ff'
  show_clock_icon: true
  show_mouse_buttons: true
  show_trial_number: true
  trial_number_position_x: 600
  trial_number_position_y: 350
  trial_number_size: 40
  trial_time: 40.0
3:
  correct_answer: Twoja odpowiedz byla poprawna
  correct_answer_color: '#008000'
  feedback: true
  feedback_position:
  - 0
  - -100
  feedback_text_size: 20
  incorrect_answer: Twoja odpowiedz byla niepoprawna. Poprawna odpowiedz jest pokazana
    powyzej
  incorrect_answer_color: '#ff0000'
  no_answer: Nie udzielono odpowiedzi. Poprawna odpowiedzi jest pokazana powyzej
  no_answer_color: '#000000'
  press_space_button_color: '#000000'
  press_space_message: Przycisnij spacje
4:
  arrowhead_length: 14
  arrowhead_width: 7
  background_color: '#dddddd'
  edges_color: '#000000'
  gap_between_edges_and_vertices: 21
  left_graph_position:
  - -130
  - 0
  right_graph_position:
  - 130
  - 0
  text_color: '#000000'
  text_size: 20
  vertices_color: '#000000'
  vertices_distance: 80
  vertices_size: 18
